"""add confidence_level to qa_logs

Revision ID: da4a5076d6e5
Revises: db989bc8a55c
Create Date: 2026-08-24 18:36:43.220193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4a5076d6e5'
down_revision: Union[str, None] = 'db989bc8a55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_logs', sa.Column('confidence_level', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_logs', 'confidence_level')
    # ### end Alembic commands ###
