"""add source_url to sources

Revision ID: db989bc8a55c
Revises: 751e4fe6cb1c
Create Date: 2026-08-24 15:39:08.727239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db989bc8a55c'
down_revision: Union[str, None] = '751e4fe6cb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('source_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'source_url')
    # ### end Alembic commands ###
